/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandRouteImport } from './routes/land'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIndexRouteImport } from './routes/property/index'
import { Route as PropertyCreateRouteImport } from './routes/property/create'

const LandRoute = LandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIndexRoute = PropertyIndexRouteImport.update({
  id: '/property/',
  path: '/property/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyCreateRoute = PropertyCreateRouteImport.update({
  id: '/property/create',
  path: '/property/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/land': typeof LandRoute
  '/property/create': typeof PropertyCreateRoute
  '/property': typeof PropertyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/land': typeof LandRoute
  '/property/create': typeof PropertyCreateRoute
  '/property': typeof PropertyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/land': typeof LandRoute
  '/property/create': typeof PropertyCreateRoute
  '/property/': typeof PropertyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/land' | '/property/create' | '/property'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/land' | '/property/create' | '/property'
  id: '__root__' | '/' | '/land' | '/property/create' | '/property/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandRoute: typeof LandRoute
  PropertyCreateRoute: typeof PropertyCreateRoute
  PropertyIndexRoute: typeof PropertyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/': {
      id: '/property/'
      path: '/property'
      fullPath: '/property'
      preLoaderRoute: typeof PropertyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/create': {
      id: '/property/create'
      path: '/property/create'
      fullPath: '/property/create'
      preLoaderRoute: typeof PropertyCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandRoute: LandRoute,
  PropertyCreateRoute: PropertyCreateRoute,
  PropertyIndexRoute: PropertyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
